remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-feed
  - jekyll-seo-tag
# Configurações específicas do tema (consulte a documentação)
just_the_docs:
  aux_links:
    "Repositório no GitHub":
      href: https://github.com/just-the-docs
