title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs
plugins: 
- jekyll-feed 
- jekyll-seo-tag
- just-the-docs
- jekyll-seo-tag
- just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

exclude:
  - Gemfile
  - Gemfile.lock
  - netlify.toml
  - node_modules
