theme: "just-the-docs"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

just_the_docs:
  aux_links:
    "Reposit처rio no GitHub":
      href: https://github.com/lopa2k/esus.pmfi

# baseurl s처 precisa do path, n찾o da URL completa
# Use isso apenas se estiver hospedando num subdiret처rio (como no GitHub Pages)
baseurl: ""  # ou "/esus.pmfi" se for em GitHub Pages
color_sheme: custom