theme: just-the-docs  # Tema principal

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-pages  # Corrigido: agora está com a indentação correta

# Configurações específicas do tema (consulte a documentação)
just_the_docs:
  aux_links:
    "Repositório no GitHub":
      href: https://github.com/just-the-docs
