[build]
  command = "gem install bundler -v 2.6.2 && bundle install && bundle exec jekyll build --trace"
  publish = "_site"

[build.environment]
  RUBY_VERSION = "3.4.2"
  BUNDLER_VERSION = "2.6.2"
  NODE_VERSION = "20"