[build]
  command = "bundle install && bundle exec jekyll build"
  publish = "_site"

[build.environment]
  RUBY_VERSION = "3.0.0"
  BUNDLER_VERSION = "2.5.9"
  NODE_VERSION = "20"  # Usa a imagem "Ubuntu Noble" (Ruby 3.2.2 incluso)
