3:43:44 PM: build-image version: 69179d37c92919bcf501ca9a8de95762ede3ffc5 (noble)
3:43:44 PM: buildbot version: 73c98606dd339ac52e94ba1d0067ad6c094040e0
3:43:45 PM: Fetching cached dependencies
3:43:45 PM: Failed to fetch cache, continuing with build
3:43:45 PM: Starting to prepare the repo for build
3:43:45 PM: No cached dependencies found. Cloning fresh repo
3:43:45 PM: git clone --filter=blob:none https://github.com/lopa2k/esus.pmfi
3:43:45 PM: Preparing Git Reference refs/heads/main
3:43:47 PM: Starting to install dependencies
3:43:47 PM: Python version set to 3.13.2
3:43:47 PM: Ruby version set to 2.7.2
3:43:47 PM: Using Bundler version 2.5.9 from Gemfile.lock
3:44:02 PM: Failed during stage 'Install dependencies': dependency_installation script returned non-zero exit code: 1
3:44:02 PM: ERROR:  Error installing bundler:
3:44:02 PM: 	There are no versions of bundler (= 2.5.9) compatible with your Ruby & RubyGems
3:44:02 PM: 	bundler requires Ruby version >= 3.0.0. The current ruby version is 2.7.2.137.
3:44:02 PM: Error installing Bundler
3:44:02 PM: Failing build: Failed to install dependencies
3:44:02 PM: Finished processing build request in 17.655s
