[build]
  command = "bundle install && bundle exec jekyll build --trace"
  environment = { 
    RUBY_VERSION = "3.1.0",  # Versão mais moderna e suportada
    BUNDLER_VERSION = "2.4.22",
    NODE_VERSION = "20"
  }
